TITLE_1: SEP0527
TITLE_2: Gestão e Organização
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SEP0527-Gestao-e-Organizacao
HERO_FILE: gestao-e-organizacao.png